export const SET_DATA_TODOS = 'SET_DATA_TODOS'
export const SET_SEARCH_DATA = 'SET_SEARCH_DATA'

// detail
export const SET_DATADETAIL = 'SET_DATADETAIL'
export const SET_DATADETAIL_LOADING = 'SET_DATADETAIL_LOADING'
export const SET_DATADETAIL_ERROR = 'SET_DATADETAIL_ERROR'

export const SET_SEARCH = 'SET_SEARCH'